### PR TITLE
fix: use graphback 0.10.0

### LINKED ISSUE #153: Update graphback to 0.10.0 stable
With the new stable version of graphback some parts have changed, in order to upgrade we will need to perform some refactoring.

#144 
#143 
#133

### PR DESCRIPTION
**Pull request by darahayes**
### Description

Resolves: #153 

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

File: src/SQLiteDatabase.ts [hunk 1]
```diff
@@ -68,7 +71,7 @@ export async function sqliteInMemoryDatabaseBuilder(
 
   // migrate the schema
   const strategy = new DropCreateDatabaseAlways("sqlite3", knex);
-  await migrate(schema, strategy);
+  await migrateDBUsingSchema(schema, strategy);
```
Comment (b1zzu) [inline src/SQLiteDatabase.ts:74]: @darahayes if the `migrateDB` method doesn't have problems with new databases, as Enda said than maybe is better to use it

**Review by b1zzu — APPROVED** [review]
LGTM

File: src/SQLiteDatabase.ts (hunk 1 above)
Comment (darahayes) [reply src/SQLiteDatabase.ts:74]: @b1zzu I think for now this is the handiest way that ensures the behaviour stays the same. If the `migrateDBUsingSchema` method changes or gets removed I'll make another PR to switch to `migrateDB` 😄
